#!/bin/ksh

# Copyright 2017 OmniOS Community Edition (OmniOSce) Association.

MIRROR=https://mirrors.omniosce.org
PROG=ipcalc
VER=0.2.0
FILE=$PROG-$VER.tar.gz
URL=$MIRROR/$PROG/$FILE

dir=`/usr/gnu/bin/mktemp -d`

(
	cd $dir
	wget $URL
	gtar -zxf $FILE
	cd $PROG-$VER
	# Remove 'ipcalc: ' prefix from error messages.
	for f in *; do
		[ -f "$f" ] || continue
		sed -i 's/"ipcalc: /"/' $f
	done
	gmake \
		CC=gcc \
		LIBS="-lsocket -lnsl -lresolv" \
		USE_GEOIP=no \
		USE_DYN_GEOIP=no \
		CFLAGS=-D_KERNEL
)

cp $dir/$PROG-$VER/$PROG .
strip $PROG

rm -rf $dir

