#!/bin/ksh

# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
# }}}

# Copyright 2018 OmniOS Community Edition (OmniOSce) Association.

SITE=https://mirrors.omniosce.org/dialog
VER=1.3-20170509
FILE=dialog-$VER.tgz
URL=$SITE/$FILE

dir=`/usr/gnu/bin/mktemp -d`

(
	cd $dir
	wget $URL
	gtar -zxf $FILE
	cd dialog-$VER
	./configure
	gmake
)

cp $dir/dialog-$VER/dialog .
strip dialog

rm -rf $dir

