#!/bin/ksh

# Copyright 2017 OmniOS Community Edition (OmniOSce) Association.

PROG=ipcalc
SITE=https://mirrors.omniosce.org/$PROG/
VER=0.2.0
URL=$SITE/$PROG-$VER.tar.gz

dir=`/usr/gnu/bin/mktemp -d`

(
	cd $dir
	wget $URL
	gtar -zxf $PROG-$VER.tar.gz
	cd $PROG-$VER
	# Remove 'ipcalc: ' prefix from all error messages
	for f in *; do
		[ -f "$f" ] || continue
		sed -i 's/"ipcalc: /"/' $f
	done
	gmake \
		CC=gcc \
		LIBS="-lsocket -lnsl -lresolv" \
		USE_GEOIP=no \
		USE_DYN_GEOIP=no \
		CFLAGS=-D_KERNEL
)

cp $dir/$PROG-$VER/ipcalc .
strip ipcalc

rm -rf $dir

