#!/bin/ksh

# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.

#
# Copyright 2012 OmniTI Computer Consulting, Inc.  All rights reserved.
# Copyright 2023 OmniOS Community Edition (OmniOSce) Association.
#

. /lib/svc/share/smf_include.sh

if [ -e "/.initialboot" ]; then
	SCRIPT=`/bin/mktemp`
	[ -n "$SCRIPT" ] || exit $SMF_EXIT_FATAL
	{
		echo "#!/bin/sh"
		cat /.initialboot
	} > $SCRIPT
	chmod 550 $SCRIPT
	echo "Applying initial boot settings..." | tee /dev/msglog
	$SCRIPT
	(( $? == SMF_EXIT_OK )) || exit $SMF_EXIT_FATAL
	mv /.initialboot /root/.initialboot~
else
	/usr/sbin/svcadm disable $SMF_FMRI
fi

exit $SMF_EXIT_OK

