#!/usr/bin/bash

#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2017 OmniTI Computer Consulting, Inc. All rights reserved.
# Copyright 2018 OmniOS Community Edition (OmniOSce) Association.
#

RPOOL=${1:-rpool}
ZFS_IMAGE=/.cdrom/image/*.zfs.bz2
keyboard_layout=${2:-US-English}
tmpf=`mktemp`

[ -n "$USE_DIALOG" ] && . /kayak/lib/dialog.sh
. /kayak/lib/utils.sh

zpool list $RPOOL >& /dev/null
if [[ $? != 0 ]]; then
   echo "Cannot find root pool $RPOOL"
   echo "Press RETURN to exit"
   read
   exit 1
fi

echo "Installing from ZFS image $ZFS_IMAGE"

. /kayak/lib/disk_help.sh
. /kayak/lib/install_help.sh

prompt_hostname omniosce
prompt_timezone

# Because of kayak's small miniroot, just use C as the language for now.
LANG=C

bename=omnios
ver=`head -1 /etc/release | awk '{print $3}'`
[ -n "$ver" ] && bename+="-$ver"

BuildBE $RPOOL $ZFS_IMAGE $bename
ApplyChanges $HOSTNAME $TZ $LANG $keyboard_layout
MakeBootable $RPOOL $bename
# Disable SSH by default for interactive installations
[ -f /kayak/etc/nossh.xml ] && \
    cp /kayak/etc/nossh.xml $ALTROOT/etc/svc/profile/site/
zpool list -v $RPOOL
echo ""
beadm list $bename
cat << EOM

$RPOOL now has a working and mounted boot environment, per above.
Once back at the main menu, you can configure the initial system settings,
reboot, or enter the shell to modify your new BE before its first boot.

EOM
echo -n "Press RETURN to go back to the menu: "
read
